# -*- coding: utf-8 -*-
"""data_fetcher.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TzOFlBaPTAggcKhZtE0Q-U3AWWN2_K0

# Fetch Data
"""

import os

os.getcwd()

## Connect your google drive
from google.colab import drive
drive.mount('/content/gdrive')

#Change the current working directory
os.chdir('/content/gdrive/My Drive/CDC_openproject')

# Print the current working directory
print("Current working directory: {0}".format(os.getcwd()))

BASE_PATH = "/content/gdrive/My Drive/CDC_openproject"

os.makedirs(f"{BASE_PATH}/images/train", exist_ok=True)
os.makedirs(f"{BASE_PATH}/images/test", exist_ok=True)

os.environ["MAPBOX_TOKEN"] = "pk.eyJ1IjoiYWRpdGlicjE2IiwiYSI6ImNtamJkY3NubzBhM3IzY3IwOXRobzg1NmYifQ.hLhAXvKfu9sBGxkZbveCVg"

import requests
import pandas as pd
import os

MAPBOX_TOKEN = os.environ["MAPBOX_TOKEN"]
STYLE = "mapbox/satellite-v9"
ZOOM = 17
IMG_SIZE = "256x256"

def fetch_image(lat, lon, save_path):
    url = f"https://api.mapbox.com/styles/v1/{STYLE}/static/{lon},{lat},{ZOOM}/{IMG_SIZE}"
    params = {"access_token": MAPBOX_TOKEN}
    r = requests.get(url, params=params)

    if r.status_code == 200:
        with open(save_path, "wb") as f:
            f.write(r.content)
    else:
        print("Error:", r.status_code)

def download_images(csv_path, out_dir):
    df = pd.read_csv(csv_path)

    for _, row in df.iterrows():
        img_path = f"{out_dir}/{int(row['id'])}.png"
        if not os.path.exists(img_path):
            fetch_image(row['lat'], row['long'], img_path)

fetch_image(47.5112, -122.257, f"{BASE_PATH}/test.png")

download_images(
    f"{BASE_PATH}/train.csv",
    f"{BASE_PATH}/images/train"
)

download_images(
    f"{BASE_PATH}/test.csv",
    f"{BASE_PATH}/images/test"
)